version: '3.7'

volumes:
  prometheus_data: {}
  grafana_data: {}

networks:
  back-tier:


services:
  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - 3000:3000
    networks:
      - back-tier
    restart: always

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./scripts/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
    ports:
      - 9090:9090
    networks:
      - back-tier
    restart: always

  statsd-exporter:
    image: prom/statsd-exporter-linux-amd64:latest
    command:
      - '--statsd.listen-udp=:8125'
    ports:
      - 9125:9125
      - 8125:8125/udp
    networks:
      - back-tier
    restart: always
    deploy:
      mode: global

  fuzzuf:
    image: ghcr.io/fuzzuf/fuzzuf/dev:latest
    volumes:
      - ./:/src/fuzzuf
    environment:
      - AFL_STATSD_HOST=statsd-exporter
      - AFL_STATSD_PORT=8125
    entrypoint: /src/fuzzuf/scripts/entrypoint.sh
    depends_on:
      - statsd-exporter
    networks:
      - back-tier
